### PR TITLE
Improvements to generation code

### LINKED ISSUE #5: Support nested module
I would like to generate code into `Foo.Gen.*`; e.g. `Foo.Gen.Agent.Client`, but the module/imports wouldn't reference the new module path.

Something like adding a `--module-prefix` flag that determines the nested modules within `--out`, e.g.
```
pinch-gen --out out/ --module-prefix 'Foo.Gen' ...
```
would generate `out/Foo/Gen/Agent/Client.hs`.

### LINKED ISSUE #6: Ignore all GHC warnings
Just add `{-# OPTIONS_GHC -w #-}` instead of manually specifying the different flags to turn off.

### PR DESCRIPTION
**Pull request by brandon-leapyear**
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:

---

Fixes #6 
Fixes #5 

Also turns on GHC warnings (cleaning up unused functions, and finding that `gTypeReference` was partial since it didn't handle `SListType`) and fix generation for `oneway void` endpoints

### CODE REVIEW

**Comment by phile314** [comment]
Thanks for the PR!

Looks good to me. The only thing missing is to add GHC 9.2 to the github workflow ( https://github.com/phile314/pinch-gen/blob/master/.github/workflows/build.yaml ), then it should be good to go.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Done

**Comment by brandonchinn178** [comment]
@phile314 seems like CI failed? the cabal file needs to bump the bounds of base

**Comment by phile314** [comment]
Yeah, I quickly fixed the constraint.

Released as https://hackage.haskell.org/package/pinch-gen-0.4.3.0 :smile:

**Pull request merged**
